package com.example.zepto.model;

import com.example.zepto.util.Pair;

import java.util.ArrayList;
import java.util.List;

/**
 * Order generated by OrderManager.
 *
 * An order may contain items supplied by one or more dark stores and
 * therefore may have one or more delivery partners.
 */
public class Order {
    private static int nextId = 1;

    public int orderId;
    public User user;
    public List<Pair<Product, Integer>> items = new ArrayList<>();
    public List<DeliveryPartner> partners = new ArrayList<>();
    public double totalAmount;

    public Order(User u) {
        orderId = nextId++;
        user = u;
        totalAmount = 0.0;
    }
}
